/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ghostsvisual;

/**
 *
 * @author Roberto Melara
 */
public class EliminarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form EliminarUsuario
     */
    public EliminarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSeguro = new javax.swing.JLabel();
        jButtonSi = new javax.swing.JButton();
        jButtonNo = new javax.swing.JButton();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(300, 180));
        setMinimumSize(new java.awt.Dimension(300, 180));
        setPreferredSize(new java.awt.Dimension(300, 180));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelSeguro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSeguro.setForeground(new java.awt.Color(251, 255, 68));
        jLabelSeguro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSeguro.setText("Seguro?");
        getContentPane().add(jLabelSeguro);
        jLabelSeguro.setBounds(190, 50, 60, 17);

        jButtonSi.setText("Si");
        jButtonSi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonSiMousePressed(evt);
            }
        });
        getContentPane().add(jButtonSi);
        jButtonSi.setBounds(190, 80, 73, 23);

        jButtonNo.setText("No");
        jButtonNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonNoMousePressed(evt);
            }
        });
        getContentPane().add(jButtonNo);
        jButtonNo.setBounds(190, 110, 73, 23);

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ghostsvisual/Prompt.png"))); // NOI18N
        getContentPane().add(jLabelBackground);
        jLabelBackground.setBounds(0, 0, 300, 150);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSiMousePressed
        //EliminarCuenta.
        MenuMiPerfil.eliminar = true;
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSiMousePressed

    private void jButtonNoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNoMousePressed
        // Regresar.
        this.setVisible(false);
    }//GEN-LAST:event_jButtonNoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNo;
    private javax.swing.JButton jButtonSi;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelSeguro;
    // End of variables declaration//GEN-END:variables
}
