/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ghostsvisual;

/**
 *
 * @author Roberto Melara
 */
public class MenuMiPerfil extends javax.swing.JFrame {
public static boolean eliminar = false; 
    /**
     * Creates new form MenuMiPerfil
     */
    public MenuMiPerfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRegresar = new javax.swing.JLabel();
        jLabelVerMisDatos = new javax.swing.JLabel();
        jLabelAjustesDeCuenta = new javax.swing.JLabel();
        jLabelEliminarCuenta = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(750, 600));
        setMinimumSize(new java.awt.Dimension(750, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ghostsvisual/Regresar.png"))); // NOI18N
        jLabelRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelRegresarMousePressed(evt);
            }
        });
        getContentPane().add(jLabelRegresar);
        jLabelRegresar.setBounds(430, 500, 300, 65);

        jLabelVerMisDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ghostsvisual/Mis Datos.png"))); // NOI18N
        jLabelVerMisDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelVerMisDatosMousePressed(evt);
            }
        });
        getContentPane().add(jLabelVerMisDatos);
        jLabelVerMisDatos.setBounds(350, 160, 320, 50);

        jLabelAjustesDeCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAjustesDeCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ghostsvisual/Ajustes.png"))); // NOI18N
        jLabelAjustesDeCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelAjustesDeCuentaMousePressed(evt);
            }
        });
        getContentPane().add(jLabelAjustesDeCuenta);
        jLabelAjustesDeCuenta.setBounds(330, 240, 360, 115);

        jLabelEliminarCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEliminarCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ghostsvisual/EliminarC.png"))); // NOI18N
        jLabelEliminarCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelEliminarCuentaMousePressed(evt);
            }
        });
        getContentPane().add(jLabelEliminarCuenta);
        jLabelEliminarCuenta.setBounds(380, 380, 260, 100);

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ghostsvisual/Sub-MenusMiPerfil.png"))); // NOI18N
        jLabelBackground.setMaximumSize(new java.awt.Dimension(750, 600));
        jLabelBackground.setMinimumSize(new java.awt.Dimension(750, 600));
        jLabelBackground.setName(""); // NOI18N
        getContentPane().add(jLabelBackground);
        jLabelBackground.setBounds(0, 0, 750, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelRegresarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegresarMousePressed
        //Regresar al menu principal.
        GhostsMenuPrincipal abrir = new GhostsMenuPrincipal();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelRegresarMousePressed

    private void jLabelEliminarCuentaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEliminarCuentaMousePressed
    //Validar seguridad de usuario.
       EliminarUsuario abrir = new EliminarUsuario();
       abrir.setVisible(true);
    //Eliminar cuenta de usuario y llevarlo al menu de inicio.
       if(eliminar == true){
           Player.usuarios[Player.posuser1] = null;
           Player.posuser1 = 0;
           GhostsMenuInicio regresar = new GhostsMenuInicio();
           regresar.setVisible(true);
           this.setVisible(false);
       }
    }//GEN-LAST:event_jLabelEliminarCuentaMousePressed

    private void jLabelVerMisDatosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVerMisDatosMousePressed
        SubmenuMisDatos abrir = new SubmenuMisDatos();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelVerMisDatosMousePressed

    private void jLabelAjustesDeCuentaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAjustesDeCuentaMousePressed
        SubmenuAjustes abrir = new SubmenuAjustes();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelAjustesDeCuentaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMiPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMiPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMiPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMiPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMiPerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAjustesDeCuenta;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelEliminarCuenta;
    private javax.swing.JLabel jLabelRegresar;
    private javax.swing.JLabel jLabelVerMisDatos;
    // End of variables declaration//GEN-END:variables
}
