/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ghostsvisual;

/**
 *
 * @author Roberto Melara
 */
public class MenuReportes extends javax.swing.JFrame {

    /**
     * Creates new form MenuReportes
     */
    public MenuReportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUlt10 = new javax.swing.JLabel();
        jLabelRegresar = new javax.swing.JLabel();
        jLabelRanking = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(750, 600));
        setMinimumSize(new java.awt.Dimension(750, 600));
        setPreferredSize(new java.awt.Dimension(750, 600));
        getContentPane().setLayout(null);

        jLabelUlt10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ghostsvisual/Ult10.png"))); // NOI18N
        jLabelUlt10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelUlt10MousePressed(evt);
            }
        });
        getContentPane().add(jLabelUlt10);
        jLabelUlt10.setBounds(330, 180, 370, 120);

        jLabelRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ghostsvisual/Regresar.png"))); // NOI18N
        jLabelRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelRegresarMousePressed(evt);
            }
        });
        getContentPane().add(jLabelRegresar);
        jLabelRegresar.setBounds(420, 490, 300, 65);

        jLabelRanking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRanking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ghostsvisual/Ranking.png"))); // NOI18N
        jLabelRanking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelRankingMousePressed(evt);
            }
        });
        getContentPane().add(jLabelRanking);
        jLabelRanking.setBounds(330, 330, 370, 130);

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ghostsvisual/Sub-MenusReportes.png"))); // NOI18N
        jLabelBackground.setMaximumSize(new java.awt.Dimension(750, 600));
        jLabelBackground.setMinimumSize(new java.awt.Dimension(750, 600));
        getContentPane().add(jLabelBackground);
        jLabelBackground.setBounds(0, 0, 750, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelRegresarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegresarMousePressed
        //Regresar al menu principal.
        GhostsMenuPrincipal abrir = new GhostsMenuPrincipal();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelRegresarMousePressed

    private void jLabelUlt10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUlt10MousePressed
        //Ir a la vista de los ultimos 10 juegos.
        SubmenuUlt10Juegos abrir = new SubmenuUlt10Juegos();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelUlt10MousePressed

    private void jLabelRankingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRankingMousePressed
        //Ir al ranking de jugadores.
        SubmenuRanking abrir = new SubmenuRanking();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelRankingMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuReportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelRanking;
    private javax.swing.JLabel jLabelRegresar;
    private javax.swing.JLabel jLabelUlt10;
    // End of variables declaration//GEN-END:variables
}
