/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ghostsvisual;

/**
 *
 * @author Roberto Melara
 */
public class SubmenuModoDeJuego extends javax.swing.JFrame {

    /**
     * Creates new form SubmenuModoDeJuego
     */
    public SubmenuModoDeJuego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAleatorio = new javax.swing.JLabel();
        jLabelManual = new javax.swing.JLabel();
        jLabelRegresar = new javax.swing.JLabel();
        jLabelSeleccion = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(750, 600));
        setMinimumSize(new java.awt.Dimension(750, 600));
        setPreferredSize(new java.awt.Dimension(750, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelAleatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ghostsvisual/Aleatorio.png"))); // NOI18N
        jLabelAleatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelAleatorioMousePressed(evt);
            }
        });
        getContentPane().add(jLabelAleatorio);
        jLabelAleatorio.setBounds(330, 250, 390, 53);

        jLabelManual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelManual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ghostsvisual/Manual.png"))); // NOI18N
        jLabelManual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelManualMousePressed(evt);
            }
        });
        getContentPane().add(jLabelManual);
        jLabelManual.setBounds(360, 320, 330, 60);

        jLabelRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ghostsvisual/Regresar.png"))); // NOI18N
        jLabelRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelRegresarMousePressed(evt);
            }
        });
        getContentPane().add(jLabelRegresar);
        jLabelRegresar.setBounds(420, 480, 300, 65);

        jLabelSeleccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSeleccion.setForeground(new java.awt.Color(251, 255, 68));
        jLabelSeleccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabelSeleccion);
        jLabelSeleccion.setBounds(334, 400, 390, 40);

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ghostsvisual/Sub-MenusMododeJuego.png"))); // NOI18N
        getContentPane().add(jLabelBackground);
        jLabelBackground.setBounds(0, 0, 751, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelRegresarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegresarMousePressed
        // Regresar al Menu de Configuracion.
        //Regresar al menu principal.
        MenuConfiguracion abrir = new MenuConfiguracion();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelRegresarMousePressed

    private void jLabelAleatorioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAleatorioMousePressed
        //Establecer Modo como Aleatorio.
        GhostsMenuPrincipal.ModoDeJuego = 0;
        //Informar al usuario del cambio.
        jLabelSeleccion.setText("Modo Aleatorio seleccionado!");
    }//GEN-LAST:event_jLabelAleatorioMousePressed

    private void jLabelManualMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelManualMousePressed
        //Establecer Modo como Aleatorio.
        GhostsMenuPrincipal.ModoDeJuego = 1;
        //Informar al usuario del cambio.
        jLabelSeleccion.setText("Modo Manual seleccionado!");
    }//GEN-LAST:event_jLabelManualMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubmenuModoDeJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubmenuModoDeJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubmenuModoDeJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubmenuModoDeJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubmenuModoDeJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAleatorio;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelManual;
    private javax.swing.JLabel jLabelRegresar;
    private javax.swing.JLabel jLabelSeleccion;
    // End of variables declaration//GEN-END:variables
}
